site_name: QuantJourney with Code
site_description: "QuantJourney with Code is a blog about quantitative finance, data science, and programming."
site_author: Jakub Polec

extra_css:
- stylesheets/extra.css

logo: logo_small_with_text_transparent.png
theme:
  name: material
  logo: images/logo_small_with_text_transparent.png
  features:
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.scroll
  - navigation.top
  - navigation.bottom
  - navigation.expand: true
  - footer
  - search
  - search.suggest
  - code-highlighting
  - edit-on-github
  - external-links
  - code-tabs
  - content-tabs
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  - tabbed-code-blocks
  language: en
  palette:
  - scheme: slate
    toggle:
      icon: material/white-balance-sunny
      name: Switch to dark mode
    primary: light blue
    accent: orange
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to light mode
    primary: blue
    accent: orange

  highlights: true
  hljs_languages:
  - python
  - bash
  - yaml
  - json

  font:
    text: Roboto
    code: Roboto Mono

nav:
- Home:
  - Overview: index.md
  - Start: doc/documentation.md
  - Strategies: strat/strategies.md
  - Backtesting: tutorials/backtesting-general.md
  - Videos: videos.md
- Documentation:
  - Overview:
    - Start: doc/documentation.md
    - Repository Installation: doc/repo.md
    - DataBase Installation: doc/installation.md
  - '_______________________': index1.md
  - Data Utils:
    - Data Manager: doc/utils/data_manager.md
    - Data Connector: doc/utils/data_connector.md
  - Assets:
    - Indices: doc/assets/indices.md
    - Crypto: doc/assets/crypto.md
    - Equities: doc/assets/equities.md
    - ETFs: doc/assets/etfs.md
    - Forex: doc/assets/forex.md
    - Futures: doc/assets/futures.md
    - Macro: doc/assets/macro.md
    - Bonds: doc/assets/bonds.md
    - Commodities: doc/assets/commodities.md
    - REITs: doc/assets/reits.md
  - Connectors:
    - CCXT Connector: doc/connectors/ccxt_connector.md
    - EOD Connector: doc/connectors/eod_connector.md
    - CNNFG Connector: doc/connectors/cnnfg_connector.md
    - FRED Connector: doc/connectors/fred_connector.md
    - Oanda Connector: doc/connectors/oanda_connector.md
    - Quandl Connector: doc/connectors/quandl_connector.md
    - SEC Connector: doc/connectors/sec_connector.md
    - Yahoo Finance Connector: doc/connectors/yf_connector.md
  - Exchanges:
    - IBKR Exchange: doc/exchanges/ibkr_exchange.md
  - '_______________________': index2.md
  - Backtesting:
    - Base Class: doc/engine/base_class.md
    - Cost Model: doc/engine/cost_model.md
    - Data Manager: doc/engine/data_manager.md
    - Execution Manager: doc/engine/execution_manager.md
    - Forecast Engine: doc/engine/forecast_engine.md
    - Market Regime: doc/engine/market_regime.md
    - Market Regime with ML: doc/engine/market_regime_with_ml.md
    - Monte Carlo Analyzer: doc/engine/monte_carlo_analyzer.md
    - Performance Analytics: doc/engine/performance_analytics.md
    - Performance Reporting: doc/engine/performance_reporting.md
    - Portfolio Construction: doc/engine/portfolio_construction.md
    - Portfolio Optimizer: doc/engine/portfolio_optimizer.md
    - Profit/Loss Tracker: doc/engine/profitloss_tracker.md
    - Risk Management: doc/engine/risk_management.md
    - Signal Generator: doc/engine/signal_generator.md
    - Transaction Cost Analysis: doc/engine/transaction_cost_analysis.md
    - Volatility Engine: doc/engine/volatility_engine.md
  - Portfolio:
    - Portfolio: portfolio/portfolio.md
- Strategies:
  - Overview: strat/strategies.md
  - Statistical Arbitrage: strat/statistical_arbitrage/overview.md
  - Momentum Investing: strat/statistical_arbitrage/momentum_investing.md
  - Mean Reversion: strat/statistical_arbitrage/mean_reversion.md
  - Machine Learning Techniques: strat/statistical_arbitrage/machine_learning.md
  - High-Frequency Trading (HFT): strat/statistical_arbitrage/hft.md
  - Factor Investing: strat/statistical_arbitrage/factor_investing.md
  - Event-Driven Strategies: strat/statistical_arbitrage/event_driven.md
- Tutorials:
  - Substack Blog: tutorials/tutorials.md
- Videos: videos.md

markdown_extensions:
- toc:
    permalink: true
    separator: "_"
    toc_depth: 3
- admonition
- codehilite
- pymdownx.superfences
- pymdownx.details
- pymdownx.emoji
- pymdownx.tasklist
- pymdownx.tilde
- pymdownx.magiclink
- pymdownx.highlight
- pymdownx.tabbed
- pymdownx.caret
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.snippets
- pymdownx.inlinehilite
- pymdownx.emoji
- pymdownx.tasklist
- pymdownx.tilde
- pymdownx.magiclink
- pymdownx.highlight
- pymdownx.tabbed
- pymdownx.caret
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.snippets
- pymdownx.inlinehilite

extra_css:
- https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap
- https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap
- https://fonts.googleapis.com/css2?family=Material+Icons&display=swap

extra_javascript:
- https://kit.fontawesome.com/7b3f6f1b5b.js


extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/jpolec/quantjourney
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/jakubpolec/
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/channel/UCe87vJTlGGtVt-UwiVQhmdQ

copyright: "&copy; 2024 <a href='https://quantjourney.substack.com' target='_blank'>jpolec</a>"
